### PR TITLE
option to build for use with delve

### PR DESCRIPTION
**Pull request by jokreliable**
### Description
Implement condition to generate a release that can be run through delve.

### CODE REVIEW

**Comment by maraino** [comment]
@jokreliable do you know why this happens:
```sh
$ go build -v -o bin/step  -gcflags="all=-N -l" -ldflags='-w' github.com/smallstep/cli/cmd/step
$ dlv exec ./bin/step
could not launch process: decoding dwarf section info at offset 0x0: too short
```
I always used:
```sh
$ dlv debug ./cmd/step/main.go
```

**Comment by jokreliable** [comment]
I was trying to generate a debug build so i could use delve remotely, without loading all the code into AWS to do it.
This allowed me to run delve and to a remote debug session from my mac to a windows AWS instance.

**Comment by jokreliable** [comment]
you need to make sure you do NOT have the `-w` when you want to run the debug builds.

**Comment by jokreliable** [comment]
> @jokreliable do you know why this happens:
> 
> ```shell
> $ go build -v -o bin/step  -gcflags="all=-N -l" -ldflags='-w' github.com/smallstep/cli/cmd/step
> $ dlv exec ./bin/step
> could not launch process: decoding dwarf section info at offset 0x0: too short
> ```

for the remote debugger to work, you need to remove the `-w` flag. (part of my change, like 30 vs 33)

**Review by maraino — APPROVED** [review]
Thanks @jokreliable, it works without the -w

**Pull request merged**
